### ISSUE TITLE
Mix of words with ALL caps and lower/otherwise is failing

### ISSUE THREAD

**Issue by foobargeez** [ap/titlecase#6]
```
$> perl
use Lingua::EN::Titlecase::Simple qw(titlecase);
my $str = 'MY NAME IS FOO BAR aLsO knoWN as geez';
print titlecase($str), "\n";

MY NAME IS FOO BAR aLsO knoWN as Geez
$>

**Comment by ap** [comment]
That’s not a bug, it’s a feature. It is expressly designed to preserve existing uppercasing in mixed-case strings, so that it will preserve existing capitalisation. If you want to forcibly re-capitalise a string from scratch, just `lc` it yourself before passing it to the function.

**Comment by foobargeez** [comment]
> just lc it yourself before passing it to the function

yep, that's what I ended up doing :-)  Thanks for the response!
