### ISSUE TITLE
Error: Can't open text to titlecase: No such file or directory at /usr/local/bin/titlecase line 60

### ISSUE THREAD

**Issue by hisaac** [ap/titlecase#7]
I'm getting a strange error when using `titlecase`, but only on one of my computers.

For example, if I try to run title case from the terminal using `titlecase "text to titlecase"`, on one of my computers it outputs as expected:

```
Text to Titlecase
```

but on my other computer I get an error saying:

```
Can't open text to titlecase: No such file or directory at /usr/local/bin/titlecase line 60.
```

Any idea why that might be? I don't know anything about perl, so I'm not sure how to debug it myself.

**Comment by ap** [comment]
It’s written as a filter, so the error is what you’d expect. For a one-liner, you’d generally say something like
````sh
echo 'text to titlecase' | titlecase
# or
titlecase <<< 'text to titlecase'
````
The odd thing is that you *don’t* get that error on the first computer.  If you care to figure out why, I’d start by checking what these say:

````sh
which titlecase
ls -l "`which titlecase`"
file "`which titlecase`"
````

**Comment by hisaac** [comment]
Thanks to those commands you suggested at the end, I've figured it out!

I ran the last one, and realized that, on the machine that _doesn't_ get an error, `titlecase` is actually a python script:

```python
#!/usr/local/opt/python/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys

from titlecase.__init__ import cmd

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cmd())
```

I honestly have no idea where I got that script. I assumed I'd installed it via homebrew just like I did on my other machine, but I must've got it somewhere else.

Anyway, thanks for your help, and sorry for the confusion.

**Comment by ap** [comment]
That’s the cover script you get when you <code>pip install <a href="https://github.com/ppannuto/python-titlecase">titlecase</a></code>.
